--고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE

--동명 동물 수 찾기
SELECT NAME, COUNT(NAME) COUNT
FROM ANIMAL_INS
GROUP BY NAME HAVING COUNT >=2
ORDER BY NAME

--입양 시각 구하기(1)
SELECT HOUR(DATETIME) 'HOUR', COUNT(*) 'COUNT'
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME) HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR

--입양 시각 구하기(2)
SET @hour := -1;

SELECT (@hour := @hour+1) as HOUR, (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) =@hour) as COUNT
FROM ANIMAL_OUTS
WHERE @hour <23